#!/usr/bin/env python3
"""Build websiteplz.com: home, trade pages, blog, sitemap, robots, IndexNow key.

EDIT PRICES, CONTACT AND CHECKOUT LINKS IN CONFIG BELOW ONLY. Then run:  python3 build.py
Every price on every page (hero, pricing, care plans, FAQ, JSON-LD) is rendered from CONFIG.
Trade copy lives in content/trades.py; blog posts in content/blog.py + content/blog/<slug>.html.
"""
import datetime, html, json, pathlib, re, sys

CONFIG = {
    "site_url": "https://websiteplz.com/",
    # --- PRICING: approved by Joshua Oct 3, 2026 -----------------------------
    "tiers": [
        {"id": "starter", "name": "Starter Page", "price": 249, "featured": False,
         "blurb": "Get online fast with a clean, phone-first page.",
         "items": ["One-page site on your domain", "Your logo, phone and cities",
                   "2 of your photos", "Click-to-call button", "Quote form",
                   "1 revision round", "Live 5 days after assets arrive"]},
        {"id": "emergency", "name": "Emergency-ready Site", "price": 1125, "featured": True,
         "blurb": "The full page built to turn visitors into calls.",
         "items": ["Everything in Starter", "Sticky call bar that stays on screen",
                   "4 of your photos", "Your 3 main services", "Reviews section",
                   "Financing line + license & insured line", "Quote / book form",
                   "2 revision rounds", "Live 5 days after assets arrive"]},
        {"id": "emergency-care", "name": "Emergency-ready + 3 Months Care", "price": 1495, "featured": False,
         "blurb": "The full site, plus we look after it for 3 months.",
         "items": ["Everything in Emergency-ready", "3 months of hosting included",
                   "2 small edits a month", "Monthly call-button and form test",
                   "Then Monthly Care at {care_monthly}/mo, optional"]},
    ],
    "care": {"monthly": 99, "quarterly": 249, "yearly": 990},
    # --- CONTACT -------------------------------------------------------------
    # hello@ forwards to Joshua's Gmail via Cloudflare Email Routing.
    "contact_email": "hello@websiteplz.com",
    # TODO: paste profile URLs once Joshua's accounts exist; empty = hidden.
    "fiverr_url": "",
    "contra_url": "",
    # --- CHECKOUT (Stripe Payment Links, being set up) ------------------------
    # Paste a checkout URL per package.
    # Empty = the Buy button scrolls to the contact form with that package preselected.
    "checkout_links": {
        "starter": "",
        "emergency": "",
        "emergency-care": "",
        "care-monthly": "",
        "care-quarterly": "",
        "care-yearly": "",
    },
    # Contact form posts here (Cloudflare Pages Function: functions/api/contact.js).
    "form_endpoint": "/api/contact",
    "samples_base": "https://goldjoshua81-dev.github.io/contractor-samples/",
    "published": "2026-10-03",   # sitemap lastmod / article dates
    # IndexNow (Bing, Yandex...): key file /<key>.txt is generated by build.py. Public by design.
    "indexnow_key": "913403c88eff0319ae020e02ea6b2994",
}


def money(n): return f"${n:,}"
C = CONFIG
care = C["care"]
care_m, care_q, care_y = care["monthly"], care["quarterly"], care["yearly"]
q_per_mo = round(care_q / 3)
y_save = care_m * 12 - care_y
y_pct = round(100 * y_save / (care_m * 12))
lowest = min(t["price"] for t in C["tiers"])
e = html.escape
SITE = C["site_url"]
ROOT = pathlib.Path(__file__).parent
sys.path.insert(0, str(ROOT / "content"))
from trades import TRADES          # noqa: E402
from blog import POSTS             # noqa: E402
TBY = {t["slug"]: t for t in TRADES}

SAMPLES = [
    ("ridgeline", "Ridge Line Heating &amp; Air", "HVAC", "hvac"),
    ("stonecreek-plumbing", "Stone Creek Plumbing Co.", "Plumbing", "plumbing"),
    ("loneoak-pressure-washing", "Lone Oak Pressure Washing", "Pressure washing", "pressure-washing"),
    ("tidypine-cleaning", "Tidy Pine Home Cleaning", "House cleaning", "cleaning"),
]

FAQ = [
    ("How fast is it?", "Your site is live 5 days after you send your logo, phone number, cities and photos. The clock starts when your assets arrive."),
    ("What's the free mockup?", "Send your business name, trade and city, and we'll make a mockup of your homepage so you can see it before you pay anything. No cost, no obligation."),
    ("Do I need a domain?", "Yes. The site goes on your own domain (about $15 a year), which you pay for and own. We walk you through connecting it."),
    ("Can you use my Facebook photos and reviews?", "Yes, as long as they're yours. Real reviews only."),
    ("Is it WordPress?", "No. It's a hand-built static page: faster, with no plugins to update and far less that can break or get hacked."),
    ("Are there monthly fees?", f"Only if you want Care. Monthly Care is {money(care_m)}/mo for hosting plus 2 small edits a month. Without Care, we hand the site off to your own host."),
    ("How many revisions do I get?", "Starter includes 1 round, the other packages include 2. A revision is a change to what's on the page, not a new design."),
    ("Do you do SEO or ads?", "We don't sell SEO packages or run ads. Every site ships with the basics done right: a clear title and description, your services and cities on the page, local business markup and a fast, mobile-friendly build. Your Google Business Profile and ads send the traffic."),
    ("What counts as a small edit?", "Anything that takes 15 minutes or less: text, hours, a price or a photo swap. Bigger changes are quoted separately, and unused edits don't roll over."),
    ("Who owns the site?", "You do. You own your domain, your content and the final page files once paid in full."),
]
FAQ_TRADE_SHARED = [FAQ[0], FAQ[1], FAQ[5], FAQ[9]]

ICONS = {
 "flame": '<path d="M12 3c.5 3.2 4.5 5.4 4.5 9.6A4.5 4.5 0 0 1 12 17a4.5 4.5 0 0 1-4.5-4.4c0-1.8.9-3.1 2-4 .1 1.6.9 2.6 1.9 2.9C11 9 11.2 5.6 12 3Z"/><path d="M5 21h14"/>',
 "drop": '<path d="M12 3.5s6 6.4 6 10.6a6 6 0 0 1-12 0C6 9.9 12 3.5 12 3.5Z"/><path d="M9.2 14.6a2.9 2.9 0 0 0 2.6 2.6"/>',
 "bolt": '<path d="M13 3 5 13.5h6L10 21l8-10.5h-6L13 3Z"/>',
 "spray": '<path d="M4 20 13.5 10.5"/><path d="M12 8.5l3.5 3.5 2.5-2.5-3.5-3.5Z"/><path d="M18 4.5h.01M20.5 7h.01M21 3.5h.01M17.2 2.3h.01"/>',
 "sparkle": '<path d="M12 3.5 13.8 9 19.5 10.8 13.8 12.6 12 18.3 10.2 12.6 4.5 10.8 10.2 9Z"/><path d="M19 16.5v4M17 18.5h4"/>',
 "phone": '<path d="M6.6 3.5h2.6l1.4 4-2 1.4a12 12 0 0 0 6.5 6.5l1.4-2 4 1.4v2.6a2 2 0 0 1-2.2 2A16.5 16.5 0 0 1 4.6 5.7a2 2 0 0 1 2-2.2Z"/>',
 "check": '<path d="m5 12.5 4.5 4.5L19 7.5"/>',
 "arrow": '<path d="M5 12h14M13 6l6 6-6 6"/>',
 "pin": '<path d="M12 21s7-6.2 7-11.5a7 7 0 0 0-14 0C5 14.8 12 21 12 21Z"/><circle cx="12" cy="9.5" r="2.5"/>',
 "star": '<path d="m12 3.8 2.5 5.2 5.7.8-4.1 4 1 5.6L12 16.7l-5.1 2.7 1-5.6-4.1-4 5.7-.8Z"/>',
 "form": '<rect x="4.5" y="3.5" width="15" height="17" rx="2.5"/><path d="M8 8.5h8M8 12h8M8 15.5h4.5"/>',
 "shield": '<path d="M12 3.5 19 6v5.6c0 4.4-3 7.6-7 8.9-4-1.3-7-4.5-7-8.9V6Z"/><path d="m9 12 2.2 2.2L15.3 10"/>',
 "gauge": '<path d="M4.5 16.5a8 8 0 1 1 15 0"/><path d="m12 13 4-4"/><circle cx="12" cy="13.5" r="1.3"/>',
 "globe": '<circle cx="12" cy="12" r="8.5"/><path d="M3.5 12h17M12 3.5c2.4 2.5 3.5 5.3 3.5 8.5s-1.1 6-3.5 8.5c-2.4-2.5-3.5-5.3-3.5-8.5S9.6 6 12 3.5Z"/>',
 "image": '<rect x="3.5" y="5" width="17" height="14" rx="2.5"/><circle cx="9" cy="10" r="1.7"/><path d="m20.5 16-4.5-4.5L7 19"/>',
 "list": '<path d="M9 7h11M9 12h11M9 17h11"/><path d="M4.5 7h.01M4.5 12h.01M4.5 17h.01"/>',
 "mail": '<rect x="3.5" y="5.5" width="17" height="13" rx="2.5"/><path d="m4 7 8 6 8-6"/>',
 "clock": '<circle cx="12" cy="12" r="8.5"/><path d="M12 7.5V12l3 2"/>',
 "key": '<circle cx="8" cy="15" r="3.5"/><path d="m10.5 12.5 8-8M15.5 7.5l2.5 2.5"/>',
}
sprite = '<svg width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false">' + "".join(
    f'<symbol id="i-{k}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">{v}</symbol>'
    for k, v in ICONS.items()) + '</svg>'
def ic(name, cls="i"): return f'<svg class="{cls}" aria-hidden="true" focusable="false"><use href="#i-{name}"/></svg>'

def ic(name, cls="i"): return f'<svg class="{cls}" aria-hidden="true" focusable="false"><use href="#i-{name}"/></svg>'
def strip(s): return re.sub(r"<[^>]+>", "", s).replace("&amp;", "&")

mailto = f'mailto:{C["contact_email"]}?subject=' + "Website%20for%20my%20business"
TRADE_OPTS = ["HVAC", "Plumbing", "Electrical", "Pressure washing", "House cleaning", "Other"]
PACKAGES = [(t["id"], f'{t["name"]} ({money(t["price"])})') for t in C["tiers"]] + [
    ("care-monthly", f"Monthly Care ({money(care_m)}/mo)"),
    ("care-quarterly", f"Quarterly Checkup ({money(care_q)}/quarter)"),
    ("care-yearly", f"Annual Refresh ({money(care_y)}/yr)"),
    ("not-sure", "Not sure yet / just a question"),
]
ORG = {"@type": "Organization", "@id": SITE + "#org", "name": "WebsitePlz", "url": SITE,
       "logo": SITE + "img/icon-512.png", "email": C["contact_email"]}

# ---------------------------------------------------------------- components
def buy_btn(pid, name, cls, label="Buy now"):
    url = C["checkout_links"].get(pid, "")
    sr = f'<span class="sr-only">: {e(name)}</span>'
    if url:
        return f'<a class="btn {cls} btn-block" href="{e(url)}" rel="noopener">{label}{sr}</a>'
    return f'<a class="btn {cls} btn-block" href="#contact" data-package="{pid}">{label}{sr}</a>'

def browser(r, slug, name, eager=False, label="Sample site", sizes="(min-width:1024px) 560px, (min-width:768px) 46vw, 92vw"):
    load = 'fetchpriority="high"' if eager else 'loading="lazy" decoding="async"'
    return (f'<div class="browser"><div class="browser-bar" aria-hidden="true"><i></i><i></i><i></i><span>{label}</span></div>'
            f'<img src="{r}img/{slug}-desktop.webp" srcset="{r}img/{slug}-desktop-640.webp 640w, {r}img/{slug}-desktop.webp 1200w" '
            f'sizes="{sizes}" width="1200" height="791" {load} alt="{name} demo site on a desktop browser"></div>')

def phone(r, slug, name, eager=False):
    load = '' if eager else 'loading="lazy" decoding="async"'
    return (f'<div class="phone"><img src="{r}img/{slug}-mobile.webp" width="390" height="844" {load} '
            f'alt="{name} demo site on a phone, with the sticky call bar"></div>')

def device(r, slug, name, eager=False, phone_slug=None, phone_name=None, note="Demo sites for fictional companies"):
    return (f'<div class="hero-media-wrap"><div class="hero-media"><div class="glow" aria-hidden="true"></div>{browser(r, slug, name, eager)}'
            f'{phone(r, phone_slug or slug, phone_name or name, eager)}</div><p class="media-note">{note}</p></div>')

def head(r, path, title, desc, og, jsonld, robots=""):
    url = SITE + path
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{e(title)}</title>
<meta name="description" content="{e(desc)}">
{robots}<link rel="canonical" href="{url}">
<meta name="theme-color" content="#0B1B2E">
<meta property="og:type" content="{'article' if path.startswith('blog/') and path != 'blog/' else 'website'}">
<meta property="og:site_name" content="WebsitePlz">
<meta property="og:title" content="{e(title)}">
<meta property="og:description" content="{e(desc)}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{SITE}img/{og}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="{e(title)}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{e(title)}">
<meta name="twitter:description" content="{e(desc)}">
<meta name="twitter:image" content="{SITE}img/{og}">
<link rel="icon" href="{r}favicon.ico" sizes="any">
<link rel="icon" href="{r}favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="{r}apple-touch-icon.png">
<link rel="manifest" href="{r}site.webmanifest">
<link rel="preload" href="{r}img/fonts/bricolage.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="{r}img/fonts/inter.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="{r}styles.css">
<script type="application/ld+json">{json.dumps(jsonld, ensure_ascii=False)}</script>
</head>
<body>
{SPRITE}
<a class="skip" href="#main">Skip to content</a>
"""

def header(r, here):
    """here = '' for home, 'trade' for trade pages (own #pricing), 'blog' for blog pages."""
    sec = "" if here in ("", "trade") else r      # same-page anchors vs. links to home
    pr = "#pricing" if here in ("", "trade") else f"{r}#pricing"
    links = [(f"{r}#trades" if here else "#trades", "Trades"), (f"{r}#samples" if here else "#samples", "Our work"),
             (pr, "Pricing"), (f"{r}blog/", "Blog"), (f"{sec}#faq" if here != "blog" else f"{r}#faq", "FAQ")]
    nav = "".join(f'<a href="{h}"{" aria-current=page" if (t == "Blog" and here == "blog") else ""}>{t}</a>' for h, t in links)
    cta = "#mockup" if here in ("", "trade") else f"{r}#mockup"
    return f"""<header class="top">
  <div class="wrap bar">
    <a class="logo" href="{r or './'}"><img src="{r}img/logo.svg" width="168" height="40" alt="WebsitePlz home"></a>
    <nav aria-label="Main">{nav}</nav>
    <a class="btn btn-primary btn-sm" href="{cta}">Free mockup</a>
  </div>
</header>
"""

def footer(r, here):
    pr = "#pricing" if here in ("", "trade") else f"{r}#pricing"
    trades = "".join(f'<a href="{r}{t["slug"]}/">{t["label"]} websites</a>' for t in TRADES)
    posts = "".join(f'<a href="{r}blog/{p["slug"]}/">{e(p["h1"][:1].upper() + p["h1"][1:])}</a>' for p in POSTS[:3])
    mob_buy = pr
    mob_mock = "#mockup" if here in ("", "trade") else f"{r}#mockup"
    return f"""<footer class="foot">
  <div class="wrap foot-grid">
    <div class="foot-brand"><img src="{r}img/logo-light.svg" width="151" height="36" alt="WebsitePlz" loading="lazy"><p>Phone-first websites for local service businesses.</p>
      <p><a href="mailto:{C['contact_email']}">{e(C['contact_email'])}</a></p></div>
    <nav class="foot-col" aria-label="Trades"><b>Trades</b>{trades}</nav>
    <nav class="foot-col" aria-label="Company"><b>WebsitePlz</b><a href="{r or './'}">Home</a><a href="{r}#samples">Our work</a><a href="{pr}">Pricing</a><a href="{r}#care">Care plans</a><a href="{r}#faq">FAQ</a><a href="{r}#mockup">Free mockup</a><a href="{r}#contact">Contact</a></nav>
    <nav class="foot-col" aria-label="Blog"><b>Blog</b>{posts}<a href="{r}blog/">All articles</a></nav>
  </div>
  <div class="wrap foot-fine">
    <p>Sample sites shown are fictional demo companies. Phone numbers, licenses, photos and reviews on them are placeholders.</p>
    <p>&copy; 2026 WebsitePlz</p>
  </div>
</footer>
<div class="mobile-bar mbar"><a class="btn btn-outline btn-block" href="{mob_buy}">Buy now</a><a class="btn btn-primary btn-block" href="{mob_mock}">Free mockup</a></div>
"""

def three_paths(r, here="", light=True):
    """Buy now / Get a free mockup / Ask a question."""
    pr = "#pricing" if here in ("", "trade") else f"{r}#pricing"
    mk = "#mockup" if here in ("", "trade") else f"{r}#mockup"
    ct = "#contact" if here in ("", "trade") else f"{r}#contact"
    q = "btn-outline-light" if light else "btn-outline"
    return (f'<div class="cta-row paths"><a class="btn btn-primary btn-lg" href="{mk}">Get a free mockup {ic("arrow")}</a>'
            f'<a class="btn {q} btn-lg" href="{pr}">Buy now</a>'
            f'<a class="text-link {"on-dark" if light else ""}" href="{ct}">Ask a question</a></div>')

def tier_html(t):
    items = "".join(f"<li>{ic('check')}<span>{x.format(care_monthly=money(care_m))}</span></li>" for x in t["items"])
    cls = "tier featured" if t["featured"] else "tier"
    badge = '<span class="badge">Most popular</span>' if t["featured"] else ""
    return (f'<article class="{cls}">{badge}<h3>{e(t["name"])}</h3>'
            f'<p class="price"><b>{money(t["price"])}</b><span>one-time</span></p>'
            f'<p class="tier-blurb">{e(t["blurb"])}</p><ul class="checks">{items}</ul>'
            f'{buy_btn(t["id"], t["name"], "btn-primary" if t["featured"] else "btn-outline")}</article>')

def pricing_sections():
    tiers = "".join(tier_html(t) for t in C["tiers"])
    li = lambda xs: "".join(f'<li>{ic("check")}<span>{x}</span></li>' for x in xs)
    return f"""<section class="section" id="pricing">
  <!-- Prices come from CONFIG in build.py. Do not edit here; run build.py. -->
  <div class="wrap">
    <div class="head"><p class="kicker">Pricing</p><h2>Simple, one-time pricing</h2>
    <p class="sub">Pay once for the site. Care is optional. Not sure yet? <a class="text-link inline" href="#mockup">Get a free mockup first.</a></p></div>
    <div class="tiers">{tiers}</div>
  </div>
</section>

<section class="section alt" id="care">
  <div class="wrap">
    <div class="head"><p class="kicker">Care plans</p><h2>We look after it, you stay on the job</h2>
    <p class="sub">Optional. We host it, test it and make small edits for you.</p></div>
    <div class="tiers care">
      <article class="tier"><h3>Monthly Care</h3><p class="price"><b>{money(care_m)}</b><span>/mo</span></p><p class="tier-blurb">Billed monthly</p>
        <ul class="checks">{li(["Hosting, SSL and form", "2 small edits a month", "Monthly test of the call button and form"])}</ul>{buy_btn('care-monthly', 'Monthly Care', 'btn-outline', 'Choose plan')}</article>
      <article class="tier"><h3>Quarterly Checkup</h3><p class="price"><b>{money(care_q)}</b><span>/quarter</span></p><p class="tier-blurb">About {money(q_per_mo)}/mo</p>
        <ul class="checks">{li(["Hosting", "Quarterly speed, link, call and form test", "New reviews and photos swapped in", "Seasonal promo line", "Up to 4 small edits a quarter"])}</ul>{buy_btn('care-quarterly', 'Quarterly Checkup', 'btn-outline', 'Choose plan')}</article>
      <article class="tier"><h3>Annual Refresh</h3><p class="price"><b>{money(care_y)}</b><span>/yr</span></p><p class="tier-blurb">Prepaid. Saves {money(y_save)} (about {y_pct}%) vs. monthly</p>
        <ul class="checks">{li(["Everything in Monthly Care", "One yearly refresh: new hero photo, updated reviews, new offers", "Speed test re-run"])}</ul>{buy_btn('care-yearly', 'Annual Refresh', 'btn-outline', 'Choose plan')}</article>
    </div>
    <p class="small muted center fine">A small edit takes 15 minutes or less (text, hours, a price, a photo swap). Unused edits don't roll over. Cancel with 30 days' notice and we hand over your files.</p>
  </div>
</section>
"""

STEPS = [("Get a free mockup", "Tell us your business, trade and city. We'll show you your homepage before you pay."),
         ("Pick a package", "Buy the package that fits. Send your logo, phone, cities, services, photos and reviews."),
         ("Review your preview", "Request changes in your included revision rounds."),
         ("Go live", "Your site goes live on your domain 5 days after your assets arrive.")]
def how_section():
    steps = "".join(f'<li><span class="num" aria-hidden="true">{n}</span><b>{t}</b><span>{d}</span></li>' for n, (t, d) in enumerate(STEPS, 1))
    return f"""<section class="section alt" id="how">
  <div class="wrap">
    <div class="head"><p class="kicker">How it works</p><h2>From mockup to live in four steps</h2></div>
    <ol class="steps">{steps}</ol>
  </div>
</section>
"""

def faq_section(items, kicker="FAQ", h="Questions"):
    body = "".join(f'<details><summary>{e(q)}<span class="plus" aria-hidden="true"></span></summary><p>{a}</p></details>' for q, a in items)
    return f"""<section class="section" id="faq">
  <div class="wrap narrow">
    <div class="head"><p class="kicker">{kicker}</p><h2>{h}</h2></div>
    <div class="faq">{body}</div>
  </div>
</section>
"""

def opts(values, selected=""):
    return "".join(f'<option{" selected" if v == selected else ""}>{v}</option>' for v in values)

def forms_section(r, trade_opt=""):
    pk = "".join(f'<option value="{pid}"{" selected" if pid == "not-sure" else ""}>{lbl}</option>' for pid, lbl in PACKAGES)
    plat = ""
    if C["fiverr_url"]: plat += f'<a class="btn btn-outline-light" href="{e(C["fiverr_url"])}" rel="noopener">Order on Fiverr</a>'
    if C["contra_url"]: plat += f'<a class="btn btn-outline-light" href="{e(C["contra_url"])}" rel="noopener">Hire on Contra</a>'
    plat = f'<div class="cta-row">{plat}</div>' if plat else ""
    req = '<span class="req" aria-hidden="true">*</span>'
    opt = '<span class="opt">(optional)</span>'
    hp = ('<div class="hp" aria-hidden="true"><label>Leave this empty<input name="company_fax" tabindex="-1" autocomplete="off"></label></div>'
          '<input type="hidden" name="t" value="">')
    status = '<div class="form-status" role="status" aria-live="polite" tabindex="-1"></div>'
    return f"""<section class="contact" id="get-started">
  <div class="wrap">
    <div class="head light"><p class="kicker light">Get started</p><h2>See your site before you pay</h2>
    <p class="lead">Ask for a free mockup of your homepage, buy a package, or just ask us a question. We reply by email.</p></div>
    <div class="form-grid">
      <form class="intake js-form" id="mockup" action="{C['form_endpoint']}" method="post" novalidate aria-labelledby="mockup-h">
        <input type="hidden" name="type" value="mockup">
        <h3 id="mockup-h">{ic("image")} Get a free mockup</h3>
        <p class="form-sub">No cost, no obligation. We'll mock up your homepage with your name and trade.</p>
        <div class="f2">
          <label>Your name {req}<input name="name" autocomplete="name" required maxlength="100"></label>
          <label>Business name {req}<input name="business" autocomplete="organization" required maxlength="120"></label>
        </div>
        <div class="f2">
          <label>Trade {req}<select name="trade" required><option value="">Choose your trade</option>{opts(TRADE_OPTS, trade_opt)}</select></label>
          <label>City {req}<input name="city" autocomplete="address-level2" required maxlength="100"></label>
        </div>
        <div class="f2">
          <label>Email {req}<input type="email" name="email" autocomplete="email" required maxlength="160"></label>
          <label>Phone {opt}<input type="tel" name="phone" autocomplete="tel" maxlength="40"></label>
        </div>
        <label>Current website or Google listing {opt}<input name="listing" inputmode="url" maxlength="300" placeholder="Link to your site, Google or Facebook page"></label>
        {hp}
        <button class="btn btn-primary btn-lg btn-block" type="submit" data-label="Send for my free mockup">Send for my free mockup</button>
        <p class="form-fine">{req} Required. We only use your details to reply to you.</p>
        {status}
      </form>
      <form class="intake js-form" id="contact" action="{C['form_endpoint']}" method="post" novalidate aria-labelledby="contact-h">
        <input type="hidden" name="type" value="contact">
        <h3 id="contact-h">{ic("mail")} Buy a package or ask a question</h3>
        <p class="form-sub">Pick a package and we'll send next steps, or just ask.</p>
        <div class="f2">
          <label>Your name {req}<input name="name" autocomplete="name" required maxlength="100"></label>
          <label>Email {req}<input type="email" name="email" autocomplete="email" required maxlength="160"></label>
        </div>
        <div class="f2">
          <label>Business name {opt}<input name="business" autocomplete="organization" maxlength="120"></label>
          <label>Phone {opt}<input type="tel" name="phone" autocomplete="tel" maxlength="40"></label>
        </div>
        <div class="f2">
          <label>Trade {opt}<select name="trade"><option value="">Choose your trade</option>{opts(TRADE_OPTS, trade_opt)}</select></label>
          <label>Package<select name="package" class="f-package">{pk}</select></label>
        </div>
        <label>Current website {opt}<input type="url" name="website" inputmode="url" placeholder="https://" maxlength="200"></label>
        <label>Message <span class="opt">(required if you didn't pick a package)</span><textarea name="message" rows="4" maxlength="3000" placeholder="Your question, the cities you serve, anything else."></textarea></label>
        {hp}
        <button class="btn btn-outline btn-lg btn-block" type="submit" data-label="Send message">Send message</button>
        <p class="form-fine">{req} Required. Prefer email? <a href="{mailto}">{e(C["contact_email"])}</a></p>
        {status}
      </form>
    </div>
    {plat}
  </div>
</section>
"""

FORM_JS = """<script>
(function(){var fallback='Sorry, the form could not be sent right now. Please email us at <a href="__MAILTO__">__EMAIL__</a>.';
document.addEventListener('click',function(ev){var a=ev.target.closest&&ev.target.closest('[data-package]');if(!a)return;var s=document.querySelector('#contact .f-package');if(s)s.value=a.getAttribute('data-package');});
Array.prototype.forEach.call(document.querySelectorAll('.js-form'),function(f){var st=f.querySelector('.form-status'),btn=f.querySelector('button[type=submit]');f.t.value=Date.now();
function show(m,ok){st.className='form-status '+(ok?'ok':'err');st.innerHTML=m;st.focus();}
f.addEventListener('submit',function(ev){ev.preventDefault();var bad=null;
 Array.prototype.forEach.call(f.querySelectorAll('input,select,textarea'),function(el){el.removeAttribute('aria-invalid');if(el.type!=='hidden'&&!el.checkValidity()){el.setAttribute('aria-invalid','true');bad=bad||el;}});
 if(f.message&&f.package&&f.package.value==='not-sure'&&!f.message.value.trim()){f.message.setAttribute('aria-invalid','true');bad=bad||f.message;}
 if(bad){show('Please check the highlighted fields.',false);bad.focus();return;}
 btn.disabled=true;btn.textContent='Sending...';
 fetch(f.action,{method:'POST',headers:{'Accept':'application/json'},body:new FormData(f)}).then(function(r){return r.json().catch(function(){return {ok:false};}).then(function(d){return [r,d];});})
 .then(function(x){var r=x[0],d=x[1];if(r.ok&&d.ok){f.reset();f.t.value=Date.now();show(f.type.value==='mockup'?'Thanks! We\\u2019ve got your details and will email you about your free mockup.':'Thanks! Your message is in. We\\u2019ll reply by email soon.',true);}else{show(r.status<500&&d.error?d.error:fallback,false);}})
 .catch(function(){show(fallback,false);}).then(function(){btn.disabled=false;btn.textContent=btn.getAttribute('data-label');});
});});})();
</script>
""".replace("__MAILTO__", mailto).replace("__EMAIL__", C["contact_email"])

INCLUDED = [
    ("phone", "Click-to-call everywhere", "A call button in the header and a bar that stays on screen while customers scroll."),
    ("image", "Your logo and photos", "Your brand, your trucks, your crew. Phone photos are fine."),
    ("list", "Your main services", "Clear cards for the jobs you want more of."),
    ("star", "Real reviews", "Reviews from your own customers, styled to build trust."),
    ("shield", "License, insured and financing lines", "The details homeowners check before they call."),
    ("form", "Quote or booking form", "For customers who would rather type than talk."),
    ("pin", "Cities you serve", "Your service area, spelled out so the right people call."),
    ("gauge", "Fast on phones", "A hand-built static page with no plugins slowing it down."),
    ("globe", "On your own domain", "You own the domain and, once paid in full, the files."),
]
def included_section(items, kicker="What's included", h="What's on the page", sub="Everything a homeowner looks for before they call, and nothing that slows the page down.", alt=False):
    li = "".join(f'<li>{ic(i, "i i-box")}<div><b>{t}</b><span>{d}</span></div></li>' for i, t, d in items)
    return f"""<section class="section{' alt' if alt else ''}" id="included">
  <div class="wrap">
    <div class="head"><p class="kicker">{kicker}</p><h2>{h}</h2><p class="sub">{sub}</p></div>
    <ul class="included">{li}</ul>
  </div>
</section>
"""

def sample_card(r, slug, name, niche, trade):
    url = C["samples_base"] + slug + "/"
    icon = TBY[trade]["icon"]
    return (f'<article class="sample"><div class="sample-media">{browser(r, slug, name, label="Demo", sizes="(min-width:768px) 40vw, 80vw")}{phone(r, slug, name)}</div>'
            f'<div class="sample-body"><span class="tag">{ic(icon)}{niche}</span><h3>{name}</h3>'
            f'<p class="muted small">Fictional demo company</p>'
            f'<div class="sample-links"><a class="text-link" href="{url}" target="_blank" rel="noopener">View live demo<span class="sr-only"> of {name} (opens in a new tab)</span> {ic("arrow")}</a>'
            f'<a class="text-link quiet" href="{r}{trade}/">{TBY[trade]["label"]} websites<span class="sr-only">: our page for {TBY[trade]["label"].lower()} businesses</span></a></div></div></article>')

def blog_cards(r, posts):
    return "".join(f'<article class="post-card"><span class="tag">{ic(TBY[p["trade"]]["icon"])}{TBY[p["trade"]]["label"]}</span>'
                   f'<h3><a href="{r}blog/{p["slug"]}/">{e(p["h1"][:1].upper() + p["h1"][1:])}</a></h3><p>{e(p["desc"])}</p>'
                   f'<span class="text-link" aria-hidden="true">Read article {ic("arrow")}</span></article>' for p in posts)

import hashlib
_H = {}
def vhash(rel):
    """Short content hash for cache-busting (the edge cache keeps /img/* for a long time)."""
    if rel not in _H:
        f = ROOT / rel
        _H[rel] = hashlib.md5(f.read_bytes()).hexdigest()[:8] if f.is_file() else ""
    return _H[rel]

ASSET_RE = re.compile(r'((?:src|href|content|srcset)=")([^"]+)(")')
def _bust_one(url, base):
    u = url.split("?v=")[0]
    if not re.search(r"\.(css|webp|png|jpg|svg|ico|woff2|webmanifest)$", u) or u.startswith(("http://", "https://")) and not u.startswith(SITE):
        return url
    rel = u[len(SITE):] if u.startswith(SITE) else (pathlib.PurePosixPath(base) / u).as_posix()
    rel = rel.lstrip("/")
    parts = []
    for seg in rel.split("/"):
        if seg == "..": parts and parts.pop()
        elif seg not in ("", "."): parts.append(seg)
    h = vhash("/".join(parts))
    return f"{u}?v={h}" if h else u

def bust(html_text, page_path):
    base = str(pathlib.PurePosixPath(page_path).parent) if "/" in page_path else ""
    def rep(m):
        val = m.group(2)
        if m.group(1) == 'srcset="':
            val = ", ".join(" ".join([_bust_one(x.split()[0], base)] + x.split()[1:]) for x in val.split(","))
        else:
            val = _bust_one(val, base)
        return m.group(1) + val + m.group(3)
    return ASSET_RE.sub(rep, html_text)

def bust_css():
    css = (ROOT / "styles.css").read_text()
    css = re.sub(r"url\((img/fonts/[a-z0-9-]+\.woff2)(?:\?v=[0-9a-f]*)?\)", lambda m: f"url({m.group(1)}?v={vhash(m.group(1))})", css)
    (ROOT / "styles.css").write_text(css)
    _H.pop("styles.css", None)

def write(path, content):
    content = bust(content, path)
    out = ROOT / path
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content)
    PAGES.append(path)

PAGES = []
SPRITE = '<svg width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false">' + "".join(
    f'<symbol id="i-{k}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round">{v}</symbol>'
    for k, v in ICONS.items()) + '</svg>'

# ---------------------------------------------------------------- pages
def trade_chooser(r):
    cards = "".join(f'<a class="trade-card" href="{r}{t["slug"]}/">{ic(t["icon"], "i tc-ico")}<b>{t["label"]}</b>'
                    f'<span>{e(strip(t["eyebrow"]).replace("Websites for ", "Sites for "))}</span><span class="tc-go" aria-hidden="true">{ic("arrow")}</span></a>' for t in TRADES)
    return f"""<section class="section chooser" id="trades">
  <div class="wrap">
    <div class="head"><p class="kicker">Pick your trade</p><h2>Built for your kind of work</h2>
    <p class="sub">Each trade gets its own layout, copy and demo. Pick yours to see what your site would look like.</p></div>
    <div class="trade-grid">{cards}</div>
  </div>
</section>
"""

def blog_teaser(r, posts, h="From the blog", sub="Practical guides to getting more calls from your website and Google listing."):
    return f"""<section class="section alt" id="blog">
  <div class="wrap">
    <div class="head"><p class="kicker">Guides</p><h2>{h}</h2><p class="sub">{sub}</p></div>
    <div class="post-grid">{blog_cards(r, posts)}</div>
    <p class="center more"><a class="text-link" href="{r}blog/">All articles {ic("arrow")}</a></p>
  </div>
</section>
"""

def build_home():
    r = ""
    title = "WebsitePlz | Websites that make the phone ring for local service pros"
    desc = (f"Phone-first websites for HVAC, plumbing, electrical, pressure washing and house cleaning businesses. "
            f"Click-to-call, your services and cities, live on your own domain in 5 days. From {money(lowest)}.")
    jsonld = {"@context": "https://schema.org", "@graph": [
        ORG,
        {"@type": "WebSite", "@id": SITE + "#website", "url": SITE, "name": "WebsitePlz", "publisher": {"@id": SITE + "#org"}},
        {"@type": "ProfessionalService", "@id": SITE + "#service", "name": "WebsitePlz", "url": SITE, "image": SITE + "img/og.png",
         "logo": SITE + "img/icon-512.png", "email": C["contact_email"], "parentOrganization": {"@id": SITE + "#org"},
         "description": "Phone-first one-page websites for local service businesses.", "priceRange": f"{money(lowest)}+",
         "makesOffer": [{"@type": "Offer", "name": t["name"], "price": t["price"], "priceCurrency": "USD"} for t in C["tiers"]]},
        {"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": strip(a)}} for q, a in FAQ]},
    ]}
    samples = "".join(sample_card(r, *s) for s in SAMPLES)
    trades_strip = "".join(f'<li><a href="{t["slug"]}/">{ic(t["icon"])}{t["label"]}</a></li>' for t in TRADES)
    page = head(r, "", title, desc, "og.png", jsonld) + header(r, "") + f"""
<main id="main">
<section class="hero" id="top">
  <div class="wrap hero-grid">
    <div class="hero-copy">
      <p class="eyebrow"><span class="dot" aria-hidden="true"></span>For local service pros</p>
      <h1>Websites that make the <em>phone ring.</em></h1>
      <p class="lead">One-page, phone-first websites for HVAC, plumbing, electrical, pressure washing and cleaning businesses. A call button that stays on screen, your services and cities, and a quote form. Live on your own domain 5 days after you send your logo and photos.</p>
      {three_paths(r)}
      <ul class="trust"><li>{ic("check")}From {money(lowest)}</li><li>{ic("check")}Live in 5 days</li><li>{ic("check")}You own your domain</li><li>{ic("check")}No WordPress or plugins</li></ul>
    </div>
    {device(r, "ridgeline", "Ridge Line Heating &amp; Air", True, "tidypine-cleaning", "Tidy Pine Home Cleaning")}
  </div>
  <div class="wrap"><ul class="trades" aria-label="Trades we build for">{trades_strip}</ul></div>
</section>
{trade_chooser(r)}
<section class="section alt" id="samples">
  <div class="wrap">
    <div class="head"><p class="kicker">Our work</p><h2>See what we build</h2>
    <p class="sub">Four live demo sites, built the way we build yours. The companies are fictional, so open one on your phone and tap around.</p></div>
    <div class="grid2">{samples}</div>
    <p class="center more"><a class="text-link" href="{C['samples_base']}" target="_blank" rel="noopener">All samples<span class="sr-only"> (opens in a new tab)</span> {ic("arrow")}</a></p>
  </div>
</section>
{included_section(INCLUDED)}{how_section()}{pricing_sections()}{faq_section(FAQ)}{blog_teaser(r, POSTS[:3])}{forms_section(r)}</main>
""" + footer(r, "") + FORM_JS + "</body>\n</html>\n"
    write("index.html", page)

def build_trade(t):
    r = "../"
    path = f'{t["slug"]}/'
    faq = [(q, a.replace("{root}", r)) for q, a in t["faq"]] + FAQ_TRADE_SHARED
    post = next(p for p in POSTS if p["slug"] == t["blog"])
    jsonld = {"@context": "https://schema.org", "@graph": [
        ORG,
        {"@type": "Service", "name": f'Websites for {t["label"].lower()} businesses', "serviceType": "Website design",
         "url": SITE + path, "provider": {"@id": SITE + "#org"}, "description": t["desc"],
         "offers": [{"@type": "Offer", "name": x["name"], "price": x["price"], "priceCurrency": "USD"} for x in C["tiers"]]},
        {"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": strip(a)}} for q, a in faq]},
        {"@type": "BreadcrumbList", "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE},
            {"@type": "ListItem", "position": 2, "name": f'{t["label"]} websites', "item": SITE + path}]},
    ]}
    pains = "".join(f'<article class="card pain"><span class="ico">{ic(["clock","phone","list"][i])}</span><h3>{e(h)}</h3><p>{e(p)}</p></article>' for i, (h, p) in enumerate(t["pains"]))
    pts = "".join(f'<li>{ic("check")}<span>{x}</span></li>' for x in t["demo_points"])
    demo_url = C["samples_base"] + t["demo"] + "/"
    others = "".join(f'<li><a href="{r}{o["slug"]}/">{ic(o["icon"])}{o["label"]}</a></li>' for o in TRADES if o is not t)
    page = head(r, path, t["title"], t["desc"], f'og-{t["slug"]}.png', jsonld) + header(r, "trade") + f"""
<main id="main">
<section class="hero trade-hero" id="top">
  <div class="wrap">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="{r}">Home</a><span aria-hidden="true">/</span><span aria-current="page">{t["label"]} websites</span></nav>
  </div>
  <div class="wrap hero-grid">
    <div class="hero-copy">
      <p class="eyebrow"><span class="dot" aria-hidden="true"></span>{t["eyebrow"]}</p>
      <h1>{t["h1"]}</h1>
      <p class="lead">{e(t["lead"])}</p>
      {three_paths(r, "trade")}
      <ul class="trust"><li>{ic("check")}From {money(lowest)}</li><li>{ic("check")}Live in 5 days</li><li>{ic("check")}You own your domain</li></ul>
    </div>
    {device(r, t["demo"], t["demo_name"], True, note=t["demo_note"])}
  </div>
</section>

<section class="section" id="why">
  <div class="wrap">
    <div class="head"><p class="kicker">The problem</p><h2>{t["pains_h"]}</h2></div>
    <div class="grid3">{pains}</div>
  </div>
</section>

<section class="section alt" id="samples">
  <div class="wrap demo-show">
    <div class="demo-media">{browser(r, t["demo"], t["demo_name"], label="Live demo", sizes="(min-width:1024px) 600px, 92vw")}{phone(r, t["demo"], t["demo_name"])}</div>
    <div class="demo-copy">
      <p class="kicker">Our work</p><h2>{t["demo_h"]}</h2>
      <p class="sub">{t["demo_note"]} Open it on your phone and tap around.</p>
      <ul class="checks">{pts}</ul>
      <div class="cta-row"><a class="btn btn-primary" href="{demo_url}" target="_blank" rel="noopener">Open the live demo<span class="sr-only"> (opens in a new tab)</span> {ic("arrow")}</a><a class="btn btn-outline" href="{r}#samples">See all demos</a></div>
    </div>
  </div>
</section>
{included_section(t["includes"], h=f'What your {t["label"].lower()} site includes', sub="Everything homeowners look for before they call, built around your trade.")}{how_section()}{pricing_sections()}{faq_section(faq, h=f'{t["label"]} website questions')}
<section class="section alt" id="blog">
  <div class="wrap">
    <div class="head"><p class="kicker">Guide</p><h2>Read before you build</h2></div>
    <div class="post-grid one">{blog_cards(r, [post])}</div>
  </div>
</section>
{forms_section(r, t["option"])}
<section class="section other-trades" aria-labelledby="other-h">
  <div class="wrap center"><h2 id="other-h" class="h-sm">Other trades we build for</h2><ul class="trades dark">{others}</ul></div>
</section>
</main>
""" + footer(r, "trade") + FORM_JS + "</body>\n</html>\n"
    write(path + "index.html", page)

def build_blog_index():
    r = "../"
    path = "blog/"
    title = "Blog: Websites and Local SEO for Service Businesses | WebsitePlz"
    desc = "Practical guides for HVAC, plumbing, electrical, pressure washing and house cleaning businesses on getting more calls from your website and Google listing."
    jsonld = {"@context": "https://schema.org", "@graph": [ORG,
        {"@type": "Blog", "name": "WebsitePlz Blog", "url": SITE + path, "publisher": {"@id": SITE + "#org"},
         "blogPost": [{"@type": "BlogPosting", "headline": p["title"], "url": f'{SITE}blog/{p["slug"]}/', "datePublished": p["date"]} for p in POSTS]},
        {"@type": "BreadcrumbList", "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE},
            {"@type": "ListItem", "position": 2, "name": "Blog", "item": SITE + path}]}]}
    page = head(r, path, title, desc, "og.png", jsonld) + header(r, "blog") + f"""
<main id="main">
<section class="hero page-hero">
  <div class="wrap narrow center">
    <nav class="crumbs" aria-label="Breadcrumb"><a href="{r}">Home</a><span aria-hidden="true">/</span><span aria-current="page">Blog</span></nav>
    <h1>Guides for local service pros</h1>
    <p class="lead">Practical, no-fluff advice on getting more calls from your website and Google listing.</p>
  </div>
</section>
<section class="section">
  <div class="wrap"><h2 class="sr-only">All articles</h2><div class="post-grid">{blog_cards(r, POSTS)}</div></div>
</section>
{cta_band(r)}</main>
""" + footer(r, "blog") + "</body>\n</html>\n"
    write(path + "index.html", page)

def cta_band(r, t=None):
    tl = f'<a class="btn btn-outline-light btn-lg" href="{r}{t["slug"]}/">{t["label"]} websites</a>' if t else f'<a class="btn btn-outline-light btn-lg" href="{r}#pricing">See pricing</a>'
    return f"""<section class="contact cta-band">
  <div class="wrap narrow center">
    <h2>Want a site that does all this?</h2>
    <p class="lead">Get a free mockup of your homepage. No cost, no obligation.</p>
    <div class="cta-row center"><a class="btn btn-primary btn-lg" href="{r}#mockup">Get a free mockup {ic("arrow")}</a>{tl}</div>
  </div>
</section>
"""

def build_post(p):
    r = "../../"
    path = f'blog/{p["slug"]}/'
    t = TBY[p["trade"]]
    body = (ROOT / "content" / "blog" / f'{p["slug"]}.html').read_text().replace("{root}", r)
    words = len(re.sub(r"<[^>]+>", " ", body).split())
    mins = max(1, round(words / 230))
    # external links open normally; mark them
    jsonld = {"@context": "https://schema.org", "@graph": [ORG,
        {"@type": "BlogPosting", "headline": p["title"], "description": p["desc"], "url": SITE + path,
         "mainEntityOfPage": SITE + path, "datePublished": p["date"], "dateModified": p["date"], "wordCount": words,
         "image": f'{SITE}img/og-{p["trade"]}.png', "author": {"@id": SITE + "#org"}, "publisher": {"@id": SITE + "#org"}},
        {"@type": "BreadcrumbList", "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE},
            {"@type": "ListItem", "position": 2, "name": "Blog", "item": SITE + "blog/"},
            {"@type": "ListItem", "position": 3, "name": p["h1"], "item": SITE + path}]}]}
    related = [x for x in POSTS if x is not p][:2]
    nice_date = datetime.date.fromisoformat(p["date"]).strftime("%B %-d, %Y")
    page = head(r, path, f'{p["title"]} | WebsitePlz', p["desc"], f'og-{p["trade"]}.png', jsonld) + header(r, "blog") + f"""
<main id="main">
<article class="post">
  <header class="hero page-hero">
    <div class="wrap narrow">
      <nav class="crumbs" aria-label="Breadcrumb"><a href="{r}">Home</a><span aria-hidden="true">/</span><a href="{r}blog/">Blog</a><span aria-hidden="true">/</span><span aria-current="page">{t["label"]}</span></nav>
      <h1>{e(p["h1"][:1].upper() + p["h1"][1:])}</h1>
      <p class="post-meta">By WebsitePlz &middot; <time datetime="{p["date"]}">{nice_date}</time> &middot; {mins} min read</p>
    </div>
  </header>
  <div class="wrap narrow prose">
{body}
    <aside class="post-cta"><b>See it on a real page</b><p>Our {t["label"].lower()} layout puts all of this on one fast, phone-first page.</p>
      <div class="cta-row"><a class="btn btn-primary" href="{r}{t["slug"]}/">{t["label"]} websites {ic("arrow")}</a><a class="btn btn-outline" href="{r}#mockup">Get a free mockup</a></div></aside>
  </div>
</article>
<section class="section alt">
  <div class="wrap"><div class="head"><h2 class="h-sm">More guides</h2></div><div class="post-grid two">{blog_cards(r, related)}</div></div>
</section>
{cta_band(r, t)}</main>
""" + footer(r, "blog") + "</body>\n</html>\n"
    write(path + "index.html", page)

def build_meta():
    d = C["published"]
    urls = [p[:-len("index.html")] for p in PAGES]
    pri = lambda u: "1.0" if u == "" else ("0.9" if u.count("/") == 1 and not u.startswith("blog") else "0.7")
    sm = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + "".join(
        f"  <url><loc>{SITE}{u}</loc><lastmod>{d}</lastmod><priority>{pri(u)}</priority></url>\n" for u in urls) + "</urlset>\n"
    (ROOT / "sitemap.xml").write_text(sm)
    (ROOT / "robots.txt").write_text(f"User-agent: *\nAllow: /\n\nSitemap: {SITE}sitemap.xml\n")
    k = C["indexnow_key"]
    (ROOT / f"{k}.txt").write_text(k)
    return urls

if __name__ == "__main__":
    bust_css()
    nf = ROOT / "404.html"
    nf.write_text(bust(nf.read_text(), "404.html"))
    build_home()
    for t in TRADES: build_trade(t)
    build_blog_index()
    for p in POSTS: build_post(p)
    urls = build_meta()
    print(f"wrote {len(PAGES)} pages:", ", ".join("/" + u for u in urls))
