"""Trade landing-page copy. Prices/links come from CONFIG in build.py, not from here.
Keep claims honest: no statistics, no client names, no testimonials."""

TRADES = [
 {
  "slug": "hvac", "label": "HVAC", "option": "HVAC", "icon": "flame",
  "demo": "ridgeline", "demo_name": "Ridge Line Heating &amp; Air",
  "title": "HVAC Websites That Get the Call | WebsitePlz",
  "desc": "Phone-first websites for HVAC companies: sticky call button, repair and install services, maintenance plans, financing and license lines. Live on your domain in 5 days.",
  "eyebrow": "Websites for HVAC companies",
  "h1": "An HVAC website that gets the <em>emergency call.</em>",
  "lead": "When the AC quits in July or the furnace dies in January, homeowners grab their phone and call the first company that looks trustworthy. We build a fast, phone-first site with a call button that never leaves the screen, so that company is you.",
  "pains_h": "Sound familiar?",
  "pains": [
   ("Leads check you out first", "Homeowners who find you on Google, Angi or Local Services Ads often look at your website before they call. A missing or dated site sends them to the next listing."),
   ("Your number is hard to find", "On a phone, a buried number or a slow page means the call goes to someone else, usually while the house is getting hotter."),
   ("Your site doesn't say what you fix", "If repair, installs, maintenance plans and the cities you serve aren't spelled out, homeowners can't tell if you're the right call."),
  ],
  "includes": [
   ("phone", "Sticky call button", "Your number in the header and a bar that stays on screen, including your after-hours line."),
   ("list", "Repair, install and maintenance", "Clear cards for the jobs you want more of, including your maintenance plan."),
   ("shield", "License, insured and financing", "Your license number, insurance line and financing offer, right where homeowners look."),
   ("pin", "Cities you serve", "Your service area spelled out, so the right homeowners call."),
   ("star", "Your real reviews", "Reviews from your own customers, styled to build trust."),
   ("form", "Book-a-visit form", "For homeowners who would rather book than call."),
  ],
  "demo_h": "See the HVAC layout live",
  "demo_points": ["Same-day and after-hours messaging up top", "Click-to-call in the header and a sticky call bar", "Repair, replacement and maintenance-plan cards", "License, insured and financing lines", "Service-area section and a book-a-visit form"],
  "demo_note": "Ridge Line Heating &amp; Air is a fictional demo company.",
  "faq": [
   ("Can you show my after-hours or emergency line?", "Yes. If you take calls nights and weekends, we say so near the top and keep the call button on screen the whole time."),
   ("Can I promote a maintenance plan?", "Yes. Your plan gets its own service card with what's included and how to sign up."),
   ("Can you add financing?", "Yes. We add your financing line and can link to your financing partner's application page."),
   ("Will this work with Local Services Ads or Google Ads?", "Yes. Point your ads or your Google Business Profile at the page, and it's built to turn those visitors into calls. We don't manage ads."),
   ("Do you build sites for electricians too?", "Yes. See our <a href=\"{root}electrical/\">electrician websites</a> page."),
  ],
  "blog": "hvac-website-checklist",
 },
 {
  "slug": "plumbing", "label": "Plumbing", "option": "Plumbing", "icon": "drop",
  "demo": "stonecreek-plumbing", "demo_name": "Stone Creek Plumbing Co.",
  "title": "Plumbing Websites Built for the Emergency Call | WebsitePlz",
  "desc": "Phone-first websites for plumbers: emergency call bar, drains, water heaters and leaks, upfront-pricing and license lines, service area and a quote form. Live in 5 days.",
  "eyebrow": "Websites for plumbers",
  "h1": "A plumbing website built for the <em>burst-pipe call.</em>",
  "lead": "Nobody shops around with water on the floor. They search, scan the first few results and call whoever looks licensed, local and ready. We build a fast, phone-first site that makes that decision easy.",
  "pains_h": "Sound familiar?",
  "pains": [
   ("Emergencies don't wait for office hours", "If your site doesn't make it obvious that you answer nights and weekends, the 2 a.m. leak goes to someone who does."),
   ("Homeowners worry about the bill", "Surprise pricing is a common fear. A clear upfront-pricing line and a quote form take that worry off the table."),
   ("Trust is the whole sale", "Your license, insurance and real reviews need to be easy to find, not buried on an About page nobody opens."),
  ],
  "includes": [
   ("phone", "Emergency call bar", "A call button that stays on screen, with your 24/7 line if you offer one."),
   ("list", "Drains, water heaters, leaks", "Service cards for the jobs you want more of, in plain language."),
   ("shield", "License and insured line", "Your license number and insurance, shown where homeowners look."),
   ("form", "Upfront pricing and quote form", "Your pricing promise plus a short form for non-urgent jobs."),
   ("pin", "Cities you serve", "Your service area, spelled out."),
   ("star", "Your real reviews", "Reviews from your own customers, styled to build trust."),
  ],
  "demo_h": "See the plumbing layout live",
  "demo_points": ["Leak, clog and no-hot-water messaging up top", "Emergency call bar that stays on screen", "Drain, water heater and repair service cards", "License, insured and upfront-pricing lines", "Service area and a request-a-plumber form"],
  "demo_note": "Stone Creek Plumbing Co. is a fictional demo company.",
  "faq": [
   ("Can I list a separate emergency number?", "Yes. We can show your main line and an emergency line, or just one number if that's simpler for you."),
   ("Can you show my license number?", "Yes. We put it in the trust bar and the footer. Use the number exactly as it appears on your state license."),
   ("Should I put prices on my site?", "It's up to you. Some plumbers list a service-call fee or starting prices; others just promise upfront pricing before work starts. We can do either."),
   ("I serve several towns. Can you list them all?", "Yes. Your service area section lists every city or county you want calls from."),
   ("Can you add water heater brands I install?", "Yes, as long as you actually install and service them. We keep it accurate."),
  ],
  "blog": "do-plumbers-need-a-website",
 },
 {
  "slug": "electrical", "label": "Electrical", "option": "Electrical", "icon": "bolt",
  "demo": "ridgeline", "demo_name": "Ridge Line Heating &amp; Air",
  "title": "Electrician Websites That Win the Job | WebsitePlz",
  "desc": "Phone-first websites for electricians: license front and center, panel upgrades, EV chargers and repairs, financing, service area and a quote form. Live in 5 days.",
  "eyebrow": "Websites for electricians",
  "h1": "An electrician website that wins the <em>panel upgrade call.</em>",
  "lead": "Homeowners want a licensed electrician they can trust inside their walls. We build a fast, phone-first site that shows your license, your services and your reviews in seconds, with a call button that never leaves the screen.",
  "pains_h": "Sound familiar?",
  "pains": [
   ("Big jobs get researched first", "Panel upgrades, EV chargers and rewires aren't impulse buys. Homeowners compare a few electricians, and a weak site loses that comparison."),
   ("Your license is invisible", "Homeowners want proof you're licensed and insured. If it's not on the page, they wonder why."),
   ("Urgent calls need a fast path", "When the power's out on half the house, a slow site with a hidden number sends the call elsewhere."),
  ],
  "includes": [
   ("shield", "License and insured, up top", "Your license number and insurance line in the header area and footer."),
   ("list", "Panels, EV chargers, repairs", "Service cards for the jobs you want, from troubleshooting to upgrades."),
   ("phone", "Sticky call button", "A call bar that stays on screen, with your emergency line if you offer one."),
   ("form", "Quote form", "For planned projects, a short form to request an estimate."),
   ("pin", "Cities you serve", "Your service area, spelled out."),
   ("star", "Your real reviews", "Reviews from your own customers, styled to build trust."),
  ],
  "demo_h": "See the layout live",
  "demo_points": ["Trust bar with license and insured lines", "Click-to-call header and sticky call bar", "Service cards you can swap for panels, EV chargers and repairs", "Financing line for larger projects", "Service-area section and a request form"],
  "demo_note": "Shown: Ridge Line Heating &amp; Air, our fictional HVAC demo. Your electrical site uses the same layout with your services, license, photos and colors.",
  "faq": [
   ("Is there an electrician demo?", "The layout shown is our HVAC demo, Ridge Line Heating &amp; Air (a fictional company). Your site uses the same layout, rewritten for electrical work with your services, photos and colors."),
   ("Can you list EV charger installs and panel upgrades?", "Yes, as long as you do that work. Each main service gets its own card."),
   ("Can you show permit and inspection info?", "Yes. If you pull permits and handle inspections, we can say so. It's a real selling point for bigger jobs."),
   ("Can you add financing for bigger projects?", "Yes. We add your financing line and can link to your financing partner's application."),
   ("Do you build for HVAC companies too?", "Yes. See our <a href=\"{root}hvac/\">HVAC websites</a> page."),
  ],
  "blog": "electrician-website-what-homeowners-check",
 },
 {
  "slug": "pressure-washing", "label": "Pressure washing", "option": "Pressure washing", "icon": "spray",
  "demo": "loneoak-pressure-washing", "demo_name": "Lone Oak Pressure Washing",
  "title": "Pressure Washing Websites That Get Booked | WebsitePlz",
  "desc": "Phone-first websites for pressure washing and soft washing businesses: free-quote button, before-and-after gallery, flat prices, service area and reviews. Live in 5 days.",
  "eyebrow": "Websites for pressure washing pros",
  "h1": "A pressure washing website that turns <em>likes into booked jobs.</em>",
  "lead": "Your before-and-after photos already do the selling on Facebook. We put them on a fast site of your own with a Get a Free Quote button, your prices and your service area, so people can book instead of scrolling past.",
  "pains_h": "Sound familiar?",
  "pains": [
   ("Your best work is buried in a feed", "Great before-and-afters on Facebook or Instagram scroll away in a day. A site keeps them front and center."),
   ("People want a price, fast", "Customers ask \"how much?\" in your DMs. A flat-price section and a quote form answer it before they lose interest."),
   ("You look like a side gig", "Without a real site, it's harder to look like a business people trust with their house, driveway or storefront."),
  ],
  "includes": [
   ("form", "Get a Free Quote button", "A quote form that asks the right questions: address, surfaces and photos."),
   ("image", "Before-and-after gallery", "Your own photos, side by side. Phone photos are fine."),
   ("list", "Services and starting prices", "House soft wash, driveways, decks and fences, with prices if you want them shown."),
   ("phone", "Click-to-call and text", "A call button that stays on screen while customers scroll."),
   ("pin", "Cities you serve", "Your service area, spelled out."),
   ("star", "Your real reviews", "Reviews from your own customers, styled to build trust."),
  ],
  "demo_h": "See the pressure washing layout live",
  "demo_points": ["Bold hero with a free-quote button", "Before-and-after gallery", "Flat-price and service cards", "Service area and reviews", "Sticky call and quote bar on phones"],
  "demo_note": "Lone Oak Pressure Washing is a fictional demo company. Its before photos are illustrative.",
  "faq": [
   ("Can I use before-and-after photos from my phone?", "Yes. Phone photos work well. Send your best pairs and we'll crop and size them for the gallery."),
   ("Should I show prices?", "Many customers like a starting price. We can show flat prices, \"starting at\" prices or just a free-quote button."),
   ("Can I run seasonal promos?", "Yes. We add a promo line, and with a Care plan we can swap it each season."),
   ("Can you link my Facebook and Instagram?", "Yes. We link your social pages so people can see more of your work."),
   ("I do residential and commercial. Can the site show both?", "Yes. We add a service card for each and say which areas you cover."),
  ],
  "blog": "pressure-washing-website-get-booked",
 },
 {
  "slug": "cleaning", "label": "House cleaning", "option": "House cleaning", "icon": "sparkle",
  "demo": "tidypine-cleaning", "demo_name": "Tidy Pine Home Cleaning",
  "title": "House Cleaning Websites Clients Book From | WebsitePlz",
  "desc": "Phone-first websites for house cleaning and maid services: Get My Price form, flat pricing by home size, bonded and insured lines, service area and reviews. Live in 5 days.",
  "eyebrow": "Websites for house cleaning businesses",
  "h1": "A house cleaning website clients can <em>book from their phone.</em>",
  "lead": "People hiring a cleaner want three things fast: a price, a reason to trust you in their home, and an easy way to book. We build a fast, phone-first site that answers all three.",
  "pains_h": "Sound familiar?",
  "pains": [
   ("\"How much for a 3-bedroom?\"", "Answering the same price question in DMs eats your evenings. A pricing section and a Get My Price form do it for you."),
   ("Trust is everything", "Clients are letting you into their home. Bonded and insured lines, real team photos and reviews make that decision easier."),
   ("Recurring clients need a reason to stay", "A clear weekly, biweekly and monthly offer, with your guarantee, turns one-time cleans into regulars."),
  ],
  "includes": [
   ("form", "Get My Price form", "Bedrooms, bathrooms and frequency, so you can quote fast."),
   ("list", "Flat pricing by home size", "Standard, deep and move-out cleans, priced the way you price them."),
   ("shield", "Bonded, insured and guarantee", "The lines that matter to people letting you into their home, shown only if they're true."),
   ("image", "Your team and your work", "Real photos of your team build trust. Phone photos are fine."),
   ("pin", "Neighborhoods you serve", "Your service area, spelled out."),
   ("star", "Your real reviews", "Reviews from your own clients, styled to build trust."),
  ],
  "demo_h": "See the cleaning layout live",
  "demo_points": ["Warm, calm design that feels trustworthy", "Get My Price button and call button", "Flat pricing by home size", "Bonded, insured and guarantee lines", "Team photo, reviews and service area"],
  "demo_note": "Tidy Pine Home Cleaning is a fictional demo company.",
  "faq": [
   ("Can you show weekly, biweekly and monthly pricing?", "Yes. We set up your pricing the way you charge, by home size, frequency or both."),
   ("Can you link to my booking software?", "Yes. If you already use an online booking tool, we can link the Book button to it. Otherwise the Get My Price form comes to you."),
   ("What should my guarantee say?", "Whatever you actually offer, for example a free re-clean if something's missed. We help you word it clearly."),
   ("Should I show my team?", "If you can, yes. Real photos of your team make people more comfortable letting you in their home."),
   ("Do you build for Airbnb or move-out cleaning businesses?", "Yes. We add service cards for turnovers, move-in and move-out cleans, or whatever you offer."),
  ],
  "blog": "house-cleaning-website-more-clients",
 },
]
